import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Header from "@/components/Header/header";
import Footer from "@/components/Footer/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>BCIT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <main className={`${styles.main}`}>
        <div className={styles.school}>
          <img src="/images/BCIT-Burnaby-Campus.jpg" alt="school" width={900} height={350}></img>
        </div>
        <div className={styles.welcome}>
          Welcome to BCIT
        </div>
        <div className={styles.different}>
          <p>Different than a college or university,</p> 
          <p>British Columbia Institute or Technology </p>
          <p>offers practice experience.</p>
        </div>
        <div className={styles.about}>
          About
        </div>
        <div className={styles.apply}>
          Ready to Apply?
        </div>
        <div className={styles.walkway}>
          <img src="/images/photo2.jpg" alt="walkway" width={150} height={150}></img>
        </div>
        <div className={styles.tuition}>
          Your tuition depends on the program you enter.
        </div>
        <div className={styles.students}>
          <img src="/images/photo1.jpg" alt="students" width={50} height={50}></img>
        </div>

      </main>

      <Footer/>
    </>
  );
}
