import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Header from "@/components/Header/header";
import Footer from "@/components/Footer/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>BCIT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <main className={`${styles.main}`}>

      </main>

      <Footer/>
    </>
  );
}
